format = '$directory$character'
right_format = '$username$hostname$localip$shlvl$singularity$kubernetes$vcsh$fossil_branch$git_branch$git_commit$git_state$git_metrics$git_status$hg_branch$pijul_channel$docker_context$package$c$cmake$cobol$daml$dart$deno$dotnet$elixir$elm$erlang$fennel$golang$guix_shell$haskell$haxe$helm$java$julia$kotlin$gradle$lua$nim$nodejs$ocaml$opa$perl$php$pulumi$purescript$python$raku$rlang$red$ruby$rust$scala$swift$terraform$vlang$vagrant$zig$buf$nix_shell$conda$meson$spack$memory_usage$aws$gcloud$openstack$azure$env_var$crystal$custom$sudo$cmd_duration$line_break$jobs$battery$time$status$os$container$shell'
add_newline = true
scan_timeout = 30
command_timeout = 500

[aws]
format = ' [$symbol($profile)( \($region\))( \[$duration\])]($style)'
symbol = '󰸏 '

[azure]
format = ' [$symbol($subscription)]($style)'
symbol = ' '

[battery]
format = ' [$symbol$percentage]($style)'
full_symbol = '󰁹 '
charging_symbol = '󰂄 '
discharging_symbol = '󰁺 '

[buf]
format = ' [$symbol($version)]($style)'
symbol = '󰚉 '

[bun]
format = ' [$symbol($version)]($style)'
symbol = '󰳮 '

[c]
format = ' [$symbol($version(-$name))]($style)'
symbol = ' '

[character]
format = '[$symbol]($style) '
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'
vimcmd_symbol = '[](bold green)'
vimcmd_replace_one_symbol = '[](bold purple)'
vimcmd_replace_symbol = '[](bold purple)'
vimcmd_visual_symbol = '[](bold yellow)'

[cmake]
format = ' [$symbol($version)]($style)'
symbol = '󰔶 '

[cobol]
format = ' [$symbol($version)]($style)'
symbol = ' '

[cmd_duration]
format = ' [$duration]($style)'
min_time = 1_000
disabled = false

[conda]
format = ' [$symbol$environment]($style)'
symbol = ' '

[container]
format = ' [$symbol\[$name\]]($style)'
symbol = ' '

[crystal]
format = ' [$symbol($version)]($style)'
symbol = ' '

[dart]
format = ' [$symbol($version)]($style)'
symbol = ' '

[deno]
format = ' [$symbol($version)]($style)'
symbol = '󰯵 '

[directory]
format = '[$path]($style)[$read_only]($read_only_style) '
truncation_length = 10
truncation_symbol = '…/'
read_only = '  '
home_symbol = ' ~'
read_only_style = 'bold red'
before_repo_root_style = 'bold purple'
repo_root_style = 'bold purple'
repo_root_format = '[󰊢 ]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) '
[directory.substitutions]
' ~/Library/Mobile Documents/com~apple~CloudDocs' = '󰀸 iCloud'
' ~/Library/CloudStorage/Dropbox' = '󰇣 Dropbox'

[docker_context]
format = ' [$symbol$context]($style)'
symbol = '󰡨 '

[dotnet]
format = ' [$symbol($version )(󰪮 $tfm)]($style)'
symbol = ' '

[elixir]
format = ' [$symbol($version \(- $otp_version\))]($style)'
symbol = ' '

[elm]
format = ' [$symbol($version)]($style)'
symbol = ' '

[env_var]
format = ' [$env_value]($style)'
symbol = '󰕕 '

[erlang]
format = ' [$symbol($version)]($style)'
symbol = ' '

[fennel]
format = ' [$symbol($version)]($style)'
symbol = '󱅽 '

[fill]
symbol = '•'

[fossil_branch]
format = ' [$symbol$branch]($style)'
symbol = ' '

[gcloud]
format = ' [$symbol$account(@$domain)(\($region\))]($style)'
symbol = '󱇶 '

[git_branch]
format = ' [$symbol$branch(:$remote_branch)]($style)'
always_show_remote = false
symbol = ' '
only_attached = true
disabled = false

[git_commit]
commit_hash_length = 32
tag_symbol = ' 󰓼 '
disabled = false

[git_state]
format = ' \([$state($progress_current/$progress_total)]($style)\)'
disabled = false

[git_metrics]
format = '( [+$added]($added_style))( [-$deleted]($deleted_style))'
disabled = false

[git_status]
format = '( [\[$all_status$ahead_behind\]]($style))'
disabled = false

[golang]
format = ' [$symbol($version)]($style)'
symbol = ' '

[guix_shell]
format = ' [$symbol]($style)'
symbol = ' '

[gradle]
format = ' [$symbol($version)]($style)'
symbol = ' '

[haskell]
format = ' [$symbol($version)]($style)'
symbol = '󰲒 '

[haxe]
format = ' [$symbol($version)]($style)'
symbol = ' '

[helm]
format = ' [$symbol($version)]($style)'
symbol = '⎈ '

[hostname]
format = ' [$ssh_symbol$hostname]($style)'
ssh_only = false
ssh_symbol = '󰀟 '
disabled = true

[java]
format = ' [${symbol}(${version})]($style)'
symbol = '󰬷 '

[jobs]
symbol = '󰫢 '

[julia]
format = ' [$symbol($version)]($style)'
symbol = ' '

[kotlin]
format = ' [$symbol($version)]($style)'
symbol = '󱈙 '

[kubernetes]
format = ' [$symbol$context( \($namespace\))]($style)'
symbol = '󱃾 '

[line_break]
disabled = false

[localip]
ssh_only = true
disabled = false

[lua]
format = ' [$symbol($version)]($style)'
symbol = '󰢱 '

[memory_usage]
format = ' $symbol [${ram}( ${swap})]($style)'
threshold = 80
symbol = '󰍛 '
disabled = false

[meson]
format = ' [$symbol$project]($style)'
symbol = '󰢘 '
truncation_symbol = '󰇘'

[hg_branch]
format = ' [$symbol$branch(:$topic)]($style)'
symbol = ' '

[nim]
format = ' [$symbol($version)]($style)'
symbol = ' '

[nix_shell]
format = ' [$symbol$state( \($name\))]($style)'
symbol = ' '

[nodejs]
format = ' [$symbol($version)]($style)'
symbol = ' '

[ocaml]
format = ' [$symbol($version )(\($switch_indicator$switch_name\))]($style)'
symbol = ' '

[opa]
format = ' [$symbol($version)]($style)'
symbol = ' '

[openstack]
format = ' [$symbol$cloud(\($project\))]($style)'
symbol = '󰈩 '

[os]
disabled = true
[os.symbols]
Alpaquita = ' '
Alpine = ' '
Amazon = ' '
Android = ' '
Arch = ' '
Artix = ' '
CentOS = ' '
Debian = ' '
DragonFly = ' '
Emscripten = ' '
EndeavourOS = ' '
Fedora = ' '
FreeBSD = ' '
Garuda = '󰛓 '
Gentoo = ' '
HardenedBSD = '󰞌 '
Illumos = '󰈸 '
Linux = ' '
Mabox = ' '
Macos = ' '
Manjaro = ' '
Mariner = ' '
MidnightBSD = ' '
Mint = ' '
NetBSD = ' '
NixOS = ' '
OpenBSD = '󰈺 '
OpenCloudOS = 'OpenCloudOS '
openEuler = 'openEuler '
openSUSE = ' '
OracleLinux = '󰌷 '
Pop = ' '
Raspbian = ' '
Redhat = ' '
RedHatEnterprise = ' '
Redox = '󰀘 '
Solus = '󰠳 '
SUSE = ' '
Ubuntu = ' '
Unknown = ' '
Windows = '󰍲 '

[package]
format = ' [$symbol$version]($style)'
symbol = '󰏗 '
display_private = true
disabled = false

[perl]
format = ' [$symbol($version)]($style)'
symbol = ' '

[php]
format = ' [$symbol($version)]($style)'
symbol = ' '

[pijul_channel]
format = ' [$symbol$channel]($style)'
symbol = ' '

[pulumi]
format = ' [$symbol($username@)$stack]($style)'
symbol = '󱗾 '

[purescript]
format = ' [$symbol($version)]($style)'
symbol = ' '

[python]
format = ' [${symbol}${pyenv_prefix}(${version})( \($virtualenv\))]($style)'
symbol = '󰌠 '

[rlang]
format = ' [$symbol($version)]($style)'
symbol = '󰟔 '

[raku]
format = ' [$symbol($version-$vm_version)]($style)'
symbol = '󱖉 '

[red]
format = ' [$symbol($version)]($style)'
symbol = '󱇋 '

[ruby]
format = ' [$symbol($version)]($style)'
symbol = ' '

[rust]
format = ' [$symbol($version)]($style)'
symbol = '󱘗 '

[scala]
format = ' [${symbol}(${version})]($style)'
symbol = ' '

[shell]
unknown_indicator = 'shell'
disabled = true

[shlvl]
threshold = 2
symbol = '󰹺 '
disabled = false

[singularity]
format = ' [$symbol\[$env\]]($style)'
symbol = '󰐙 '

[solidity]
format = ' [$symbol($version)]($style)'
symbol = '󰅪 '

[spack]
format = ' [$symbol$environment]($style)'
symbol = '󰊳 '

[status]
format = ' [$symbol]($style)'
symbol = '[✗](bold red)'
success_symbol = '[✔](bold green)'
not_executable_symbol = '[](bold red)'
not_found_symbol = '[](bold yellow)'
sigint_symbol = '[✘](bold red)'
signal_symbol = '[](bold yellow)'
pipestatus_separator = ''
pipestatus_format = '$pipestatus [$symbol$common_meaning$signal_name$maybe_int]($style)'
recognize_signal_code = true
pipestatus = false
map_symbol = true
disabled = true

[sudo]
format = ' [$symbol]($style)'
symbol = ''

[swift]
format = ' [$symbol($version)]($style)'
symbol = ' '

[terraform]
format = ' [$symbol$workspace]($style)'
symbol = ' '

[time]
format = ' [$time]($style)'
utc_time_offset = 'local'
use_12hr = false
disabled = true

[username]
format = ' [$user]($style)'
show_always = true
disabled = true

[vagrant]
format = ' [$symbol($version)]($style)'
symbol = ' '

[vlang]
format = ' [$symbol($version)]($style)'
symbol = '󱂌 '

[vcsh]
format = ' [$symbol$repo]($style)'
symbol = ' '

[zig]
format = ' [$symbol($version)]($style)'
symbol = ' '
